'use strict';
const $ = id => document.getElementById(id);
const state = {data:null,catalog:null,auto:true,fetching:false,token:sessionStorage.getItem('relay.token')||'',base:sessionStorage.getItem('relay.base')||location.origin,device:readStored('relay.device'),inspection:null,tab:'result',result:'',latestId:null,busy:false};
const names = {overview:'运行概览',records:'连接与请求',workbench:'接口工作台',fields:'API 与数据字段',connect:'接入书源'};
const ops = {discovery_menu:'分类与分组',review_summary:'段评数量',reviews:'书评与讨论',review_replies:'评论回复',shelf_change:'书架增删',search:'搜索',detail:'书籍详情',chapters:'完整目录',content:'章节正文',content_batch:'批量正文',progress_get:'读取云端章节',progress_put:'上传阅读章节',explore:'发现列表',raw:'官方 API',web_login:'网页登录',invalid:'无效请求',transform_chapters:'目录转换'};
function readStored(key){try{return JSON.parse(sessionStorage.getItem(key)||'null');}catch{return null;}}
function text(id,value){$(id).textContent=value;}
function el(tag,className,value){const node=document.createElement(tag);if(className)node.className=className;if(value!==undefined)node.textContent=value;return node;}
function icon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');const use=document.createElementNS('http://www.w3.org/2000/svg','use');use.setAttribute('href','#i-'+name);svg.append(use);return svg;}
function number(v){return new Intl.NumberFormat('zh-CN').format(v||0);}
function bytes(v){return v>=1048576?(v/1048576).toFixed(2)+' MiB':v>=1024?(v/1024).toFixed(1)+' KiB':v+' B';}
function duration(ms){return ms>=3600000?Math.floor(ms/3600000)+' 小时 '+Math.floor(ms%3600000/60000)+' 分钟':ms>=60000?Math.floor(ms/60000)+' 分 '+Math.floor(ms%60000/1000)+' 秒':Math.floor(ms/1000)+' 秒';}
function runtimeRows(d){const m=d.service.memory||{},mem=v=>v==null?'暂不可用':bytes(v);return [['平台',(d.service.platform==='windows'?'Windows':d.service.platform)+' · '+d.service.arch],['已运行',duration(d.uptimeMs)],['进程物理内存',mem(m.residentBytes)],['物理内存峰值',mem(m.peakResidentBytes)],['私有提交内存',mem(m.privateBytes)],['诊断数据大小',bytes(d.detailBytes)+' / '+bytes(d.detailBudget)],['上游请求',number(d.upstreamTotal)+' 次'],['官方接口 DNS','阿里 DoH · IPv6 优先'],['响应传输','gzip 压缩已启用'],['全局并发',d.service.concurrency+' 个请求'],['同设备正文',d.service.contentConcurrencyPerDevice+' 个请求 · 每批 '+d.service.contentBatchSize+' 章'],['批次最短间隔',(d.service.batchIntervalMs||0)+' ms'],['响应缓存','关闭 · 实时请求']];}
function clock(ms){return new Date(ms).toLocaleTimeString('zh-CN',{hour12:false});}
function timeLabel(ms){return new Date(ms).toLocaleTimeString('zh-CN',{hour12:false,hour:'2-digit',minute:'2-digit'});}
function toast(message){text('toast',message);$('toast').hidden=false;clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
async function copy(value){try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(value);else{const input=el('textarea');input.value=value;input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();const copied=document.execCommand('copy');input.remove();if(!copied)throw new Error('浏览器不支持复制');}toast('已复制到剪贴板');}catch(e){toast('复制失败，请手动选择链接复制');}}
function headers(extra={}){return {...(state.token?{Authorization:'Bearer '+state.token}:{}),...extra};}
async function fetchApi(url,options={}){const response=await fetch(url,{...options,headers:headers(options.headers||{}),cache:'no-store'});const raw=await response.text();if(!response.ok){let message=raw;try{const data=JSON.parse(raw);message=data.error||raw;if(data.code==='TOKEN_REQUIRED')message='服务启用了访问令牌，请点击右上角“服务令牌”填写。';}catch{}const err=new Error(message);err.status=response.status;err.response=response;throw err;}return {response,raw};}
function setPage(){const page=location.hash.slice(1);const chosen=names[page]?page:'overview';document.querySelectorAll('.page').forEach(section=>section.hidden=section.id!=='page-'+chosen);document.querySelectorAll('[data-page]').forEach(link=>link.classList.toggle('active',link.dataset.page===chosen));text('breadcrumb-page',names[chosen]);document.title=names[chosen]+' · 番茄中转';}
window.addEventListener('hashchange',setPage);setPage();
async function refresh(){if(state.fetching)return;state.fetching=true;$('refresh').classList.add('spin');try{const {raw}=await fetchApi('/admin/status');state.data=JSON.parse(raw);$('connection-warning').hidden=true;renderStatus();text('updated','更新于 '+clock(Date.now()));text('sidebar-status','服务运行中');text('service-state','服务运行中');$('sidebar-dot').classList.remove('off');if(!state.catalog){try{state.catalog=JSON.parse((await fetchApi('/admin/catalog')).raw);renderCatalog();updateArguments();}catch(e){toast(e.message);}}}catch(e){text('connection-warning',e.message||'服务连接中断，请检查中转服务是否仍在运行。');$('connection-warning').hidden=false;text('sidebar-status','服务连接中断');text('service-state','连接中断');$('sidebar-dot').classList.add('off');}finally{state.fetching=false;$('refresh').classList.remove('spin');}}
function renderStatus(){const d=state.data;text('stat-api',number(d.apiTotal));text('nav-count',number(d.apiTotal));text('stat-tcp',number(d.tcpTotal));text('stat-active',d.apiActive+' 个处理中');text('stat-tcp-active','当前 '+d.tcpActive+' 个连接');text('stat-rate',d.successRate.toFixed(1));text('stat-success','成功 '+number(d.succeeded));text('stat-failed','失败 '+number(d.failed));text('stat-ms',number(d.averageMs));text('stat-p50','P50 '+d.p50Ms+' ms');text('stat-p95','P95 '+d.p95Ms+' ms');text('sidebar-version',(d.service.platform==='windows'?'Windows':d.service.platform)+' · v'+d.service.version);text('footer-version','v'+d.service.version);renderTrend(d.trend);renderOperations(d.operations);renderRequests($('recent-requests'),d.requests.slice(0,5));renderAllRequests();renderConnections(d.connections);text('connections-active',d.tcpActive+' 个活跃');const runtime=$('runtime');runtime.replaceChildren();for(const [key,value] of runtimeRows(d)){const row=el('div');row.append(el('span',null,key),el('strong',null,value));runtime.append(row);}const automaticBase=d.service.configuredPublicUrl||location.origin;if(!sessionStorage.getItem('relay.base')&&state.base!==automaticBase){state.base=automaticBase;renderSource();}if(state.tokenEnabled!==d.service.tokenEnabled){state.tokenEnabled=d.service.tokenEnabled;renderSource();}text('overview-address',state.base);}
function renderTrend(points){const wrap=$('trend');const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 660 176');svg.setAttribute('role','img');svg.setAttribute('aria-label','最近十五分钟的 API 请求数');const max=Math.max(4,...points.map(p=>p.count));function s(tag,attrs,content){const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(content)n.textContent=content;svg.append(n);return n;}for(let i=0;i<3;i++){const y=16+i*58;s('line',{x1:30,x2:640,y1:y,y2:y,stroke:'var(--chart-grid)','stroke-dasharray':'3 4'});s('text',{x:5,y:y+3},String(Math.round(max*(1-i/2))));}const coords=points.map((p,i)=>[40+i*42.3,132-p.count/max*116]);s('path',{d:'M'+coords.map(p=>p.join(',')).join(' L')+' L'+coords.at(-1)[0]+',132 L40,132 Z',fill:'var(--chart-area)',stroke:'none'});s('path',{d:'M'+coords.map(p=>p.join(',')).join(' L'),stroke:'var(--chart-stroke)','stroke-width':2,fill:'none'});coords.forEach(([x,y],i)=>{const c=s('circle',{cx:x,cy:y,r:2.5,fill:'var(--chart-point)',stroke:'var(--chart-stroke)','stroke-width':1.5});const title=document.createElementNS(ns,'title');title.textContent=timeLabel(points[i].time)+' · '+points[i].count+' 次请求';c.append(title);});[0,4,9,14].forEach(i=>s('text',{x:coords[i][0],y:164,'text-anchor':'middle'},timeLabel(points[i].time)));wrap.replaceChildren(svg);}
function renderOperations(counts){const wrap=$('operations');wrap.replaceChildren();const list=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5);if(!list.length){wrap.append(el('div','empty','暂无请求，去接口工作台发起一次试试。'));return;}const total=Object.values(counts).reduce((a,b)=>a+b,0);for(const [op,count]of list){const row=el('div','operation-row'),label=el('div','operation-label'),bar=el('div','operation-bar'),fill=el('i');label.append(el('span',null,ops[op]||op),el('span',null,count+' · '+Math.round(count/total*100)+'%'));fill.style.width=(count/total*100)+'%';bar.append(fill);row.append(label,bar);wrap.append(row);}}
function renderRequests(tbody,rows){tbody.replaceChildren();if(!rows.length){const row=el('tr'),cell=el('td','empty-cell');cell.colSpan=6;const empty=el('div','empty');empty.append(el('h3',null,'还没有符合条件的请求'),el('p',null,'导入书源，或在接口工作台发送请求后，记录会显示在这里。'));cell.append(empty);row.append(cell);tbody.append(row);return;}for(const r of rows){const row=el('tr','request-row');row.dataset.id=r.id;row.tabIndex=0;row.setAttribute('aria-label','查看请求 '+r.id+' '+(ops[r.operation]||r.operation));const op=el('td');op.append(el('span','request-op',ops[r.operation]||r.operation),el('span','request-summary',r.summary||('请求 #'+r.id)));const client=el('td');client.append(el('span',null,r.client),el('span','client-sub',r.peer));const status=el('td');const badge=el('span','status-badge'+(r.status>=400?' fail':''));badge.append(el('span','dot'+(r.status>=400?' off':'')),document.createTextNode(String(r.status)));status.append(badge);const ms=el('td','numeric',r.elapsedMs+' ms'),time=el('td',null,clock(r.startedMs)),action=el('td');const arrow=icon('arrow');arrow.classList.add('row-arrow');action.append(arrow);row.append(op,client,status,ms,time,action);row.addEventListener('click',()=>inspect(r.id));row.addEventListener('keydown',e=>{if(e.key==='Enter')inspect(r.id);});tbody.append(row);}}
function renderAllRequests(){if(!state.data)return;const q=$('record-search').value.toLowerCase(),status=$('record-status').value;const rows=state.data.requests.filter(r=>(r.summary+' '+r.client+' '+r.peer+' '+r.operation).toLowerCase().includes(q)&&(status==='all'||(status==='success'?r.status<400:r.status>=400)));text('record-count',rows.length+' 条匹配 · 详情内存 '+bytes(state.data.detailBytes)+' / '+bytes(state.data.detailBudget));renderRequests($('all-requests'),rows);}
function renderConnections(rows){const tbody=$('connections');tbody.replaceChildren();for(const r of rows){const row=el('tr');const badge=el('span','status-badge');badge.textContent=r.closedMs?'已结束':'连接中';if(r.closedMs)badge.classList.add('closed');const status=el('td');status.append(badge);row.append(el('td','numeric','#'+r.id),el('td','numeric',r.peer),el('td',null,clock(r.openedMs)),el('td',null,duration((r.closedMs||Date.now())-r.openedMs)),status);tbody.append(row);}}
function validBase(value){const url=new URL(value.trim());if(!['http:','https:'].includes(url.protocol)||url.username||url.password||url.pathname!=='/'||url.search||url.hash)throw new Error('请填写 HTTP/HTTPS 服务地址，不要包含路径或查询参数');return url.origin;}
function renderSource(){if(!state.base)return;$('public-base').value=state.base;const source=state.base+'/source.json?base='+encodeURIComponent(state.base);text('source-url',source);text('qr-address',state.base);text('overview-address',state.base);$('qr-image').src='/qr.svg?base='+encodeURIComponent(state.base);$('import-source').href='legado://import/bookSource?src='+encodeURIComponent(source);const token=state.data&&state.data.service.tokenEnabled;const local=new URL(state.base).hostname;const hint=token?'服务已启用令牌。请下载 JSON 书源文件后导入，文件会包含服务令牌。':['127.0.0.1','localhost','[::1]'].includes(local)?'这是本机地址。手机导入时请用手机可访问的域名或主机 IP 打开控制台，或在此填写地址。':'已自动使用当前访问地址，域名、端口和 HTTPS 会一同写入书源；也可手动修改。';text('address-hint',hint);$('import-source').hidden=!!token;}
function download(content,name,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function renderCatalog(){const cards=$('metadata-cards');cards.replaceChildren();for(const [title,key,i]of [['书籍与阅读记录','book','book'],['章节与目录','chapter','layers'],['正文与精确 ID','body','code']]){const card=el('article','card metadata-card');card.append(icon(i),el('h2',null,title),el('p',null,state.catalog.metadata[key]));if(key==='body')card.append(el('p',null,state.catalog.metadata.ids));cards.append(card);}const catalog=$('api-catalog');catalog.replaceChildren();for(const api of state.catalog.paths){const card=el('button','catalog-card');card.append(el('span','method-badge',api.method||'GET'));const body=el('div');body.append(el('strong',null,api.name),el('code',null,api.path));card.append(body,icon('arrow'));card.addEventListener('click',()=>{$('operation').value=api.operation||'raw';updateArguments();if(!api.operation){$('arg-path').value=api.path;$('arg-params').value=JSON.stringify(api.params,null,2);}syncRequest();location.hash='workbench';});catalog.append(card);}}
function addInput(wrap,id,label,value,type='text'){const node=el('label',null,label),input=el('input');input.id=id;input.type=type;input.value=value;node.append(input);wrap.append(node);input.addEventListener('input',syncRequest);return input;}
function updateArguments(){const op=$('operation').value,wrap=$('argument-fields');wrap.replaceChildren();if(featureFields(op,wrap))return;if(op==='search')addInput(wrap,'arg-key','搜索关键词','烟雨楼');if(['detail','chapters','content','content_batch','progress_get','progress_put'].includes(op))addInput(wrap,'arg-book','书籍 ID 或地址','6883748331202284558');if(['content','progress_put'].includes(op))addInput(wrap,'arg-chapter','章节 ID 或地址','6883749008234250760');if(op==='content_batch')addInput(wrap,'arg-items','章节 ID，逗号分隔（最多 30 个）','6883749008234250760');if(op==='progress_put'){addInput(wrap,'arg-index','章节索引（从 0 开始）','0','number');addInput(wrap,'arg-base','上次云端 timestampMs（必填，防止覆盖新进度）','0','number');}if(op==='explore'){const label=el('label',null,'发现入口'),select=el('select');select.id='arg-url';for(const [value,name]of [['category?gender=1&id=7','男生玄幻分类'],['category?gender=0&id=280','女生分类'],['ranking?gender=1&algo=200','巅峰榜'],['home','首页推荐'],['cell/125','猜你喜欢'],['cell/119','高分佳作'],['rank/0','完本榜'],['rank/1','推荐榜'],['rank/2','番茄榜'],['rank/3','黑马榜'],['shelf','我的书架（需登录）'],['history','阅读历史（需登录）']]){const option=el('option',null,name);option.value='fanqie://'+value;select.append(option);}select.addEventListener('change',syncRequest);label.append(select);wrap.append(label);}if(op==='explore'){const label=el('label',null,'分类筛选（JSON，可选）'),input=el('textarea');input.id='arg-preferences';input.rows=4;input.value='{}';input.addEventListener('input',syncRequest);label.append(input);wrap.append(label);}if(['search','explore'].includes(op)){const input=addInput(wrap,'arg-page','页码','1','number');input.min='1';input.max='2147483647';}if(op==='raw'){const label=el('label',null,'官方接口'),select=el('select');select.id='arg-path';for(const api of (state.catalog?.paths||[]).filter(api=>!api.operation)){const option=el('option',null,api.name);option.value=api.path;select.append(option);}select.addEventListener('change',()=>{const api=state.catalog.paths.find(api=>api.path===select.value);$('arg-params').value=JSON.stringify(api.params,null,2);syncRequest();});label.append(select);wrap.append(label);const params=el('label',null,'查询参数（JSON）'),input=el('textarea');input.id='arg-params';input.rows=6;input.spellcheck=false;input.value=JSON.stringify(state.catalog?.paths[0]?.params||{},null,2);input.addEventListener('input',syncRequest);params.append(input);wrap.append(params);}syncRequest();}
function makePayload(){const operation=$('operation').value;let args={};if(isFeature(operation))return featureRequest(operation);if(operation==='search')args={key:$('arg-key').value,page:Number($('arg-page').value)||1};if(['detail','chapters','content','content_batch','progress_get','progress_put'].includes(operation)){const raw=$('arg-book').value.trim();args.book={bookUrl:raw.startsWith('http')?raw:'https://fanqienovel.com/page/'+raw};}if(['content','progress_put'].includes(operation)){const raw=$('arg-chapter').value.trim();args.chapter={url:raw.startsWith('http')?raw:'https://fanqienovel.com/reader/'+raw};}if(operation==='content_batch')args.chapters=$('arg-items').value.split(',').map(x=>({url:'https://fanqienovel.com/reader/'+x.trim()}));if(operation==='progress_put'){args.chapterIndex=Number($('arg-index').value);args.timestampMs=Date.now();args.baseTimestampMs=Number($('arg-base').value);}if(operation==='explore')args={url:$('arg-url').value,page:Number($('arg-page').value)||1,preferences:JSON.parse($('arg-preferences').value)};if(operation==='raw')args={path:$('arg-path').value,params:JSON.parse($('arg-params').value)};return {operation,args,device:state.device||{deviceType:'Android',deviceBrand:'Generic'},osVersion:'13'};}
function syncRequest(){try{const payload=makePayload();let previous;try{previous=JSON.parse($('request-json').value);}catch{}if(previous?.account)payload.account=previous.account;$('request-json').value=JSON.stringify(payload,null,2);}catch{}}
function rememberDevice(response){const next=response?.headers.get('x-fanqie-state');if(!next)return;try{state.device=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(next),c=>c.charCodeAt(0))));sessionStorage.setItem('relay.device',JSON.stringify(state.device));}catch{}}
async function sendRequest(e){e.preventDefault();if(state.busy)return;let payload;try{payload=JSON.parse($('request-json').value);}catch{toast('完整请求不是有效 JSON，请检查参数');return;}state.busy=true;const button=$('send-request');button.disabled=true;button.replaceChildren(icon('refresh'),document.createTextNode('正在请求…'));button.classList.add('spin');const started=performance.now();text('request-timing','正在获取实时数据');try{const {raw,response}=await fetchApi('/v1/call',{method:'POST',headers:{'Content-Type':'application/json','X-Relay-Client':'Web'},body:JSON.stringify(payload)});rememberDevice(response);const metrics=JSON.parse(response.headers.get('x-fanqie-metrics')||'{}');state.result=raw;$('workbench-empty').hidden=true;$('workbench-result').hidden=false;$('result-download').disabled=false;text('result-caption','HTTP '+response.status+' · '+(ops[payload.operation]||payload.operation)+' · 实时数据');text('result-size',bytes(new TextEncoder().encode(raw).length));renderMetrics($('result-metrics'),metrics,Math.round(performance.now()-started));previewResult(false);await refresh();state.latestId=Number(response.headers.get('x-fanqie-request-id'))||state.data?.requests.find(r=>r.client==='Web'&&r.operation===payload.operation)?.id;payload.device=state.device;$('request-json').value=JSON.stringify(payload,null,2);}catch(err){rememberDevice(err.response);if(state.device)payload.device=state.device;$('request-json').value=JSON.stringify(payload,null,2);text('result-caption','请求失败 · '+(err.status||'连接错误'));$('workbench-empty').hidden=true;$('workbench-result').hidden=false;text('result-preview',err.message);state.result=JSON.stringify({error:err.message},null,2);$('result-download').disabled=false;$('expand-result').hidden=true;renderMetrics($('result-metrics'),{},Math.round(performance.now()-started));await refresh();state.latestId=Number(err.response?.headers.get('x-fanqie-request-id'))||null;text('result-size',bytes(new TextEncoder().encode(state.result).length));}finally{state.busy=false;button.disabled=false;button.classList.remove('spin');button.replaceChildren(icon('play'),document.createTextNode('发送请求'));text('request-timing',Math.round(performance.now()-started)+' ms');}}
function previewResult(full){const max=12000;text('result-preview',full?state.result:state.result.slice(0,max));$('expand-result').hidden=full||state.result.length<=max;$('expand-result').textContent='展示完整结果（当前显示前 '+number(max)+' 个字符）';}
function renderMetrics(wrap,m,total){wrap.replaceChildren();for(const [label,value]of [['总耗时',total+' ms'],['排队',(m.queueMs||0)+' ms'],['批次等待',(m.batchWaitMs||0)+' ms'],['官方 HTTP',(m.httpMs||0)+' ms'],['签名',(m.signUs||0)+' μs'],['转换',((m.transformUs||0)/1000).toFixed(2)+' ms'],['上游',((m.requests||[]).length)+' 次']]){const node=el('span',null,label);node.append(el('strong',null,value));wrap.append(node);}}
async function inspect(id){try{const {raw}=await fetchApi('/admin/requests/'+id);state.inspection=JSON.parse(raw);state.tab='result';const d=state.inspection;text('inspect-id','REQUEST #'+id+' · '+d.record.client);text('inspect-title',(ops[d.record.operation]||d.record.operation)+' · '+d.record.status);renderMetrics($('inspect-summary'),d.metrics,d.record.elapsedMs);const select=$('upstream-select');select.replaceChildren();const result=el('option',null,'阅读输出');result.value='result';select.append(result);d.upstream.forEach((t,i)=>{const option=el('option',null,t.path+' · '+t.status+(t.credentialsHidden?' · 已隐藏凭证':''));option.value=String(i);select.append(option);});select.value=d.upstream.length?String(d.upstream.length-1):'result';$('field-search').value='';renderInspection();$('inspector').showModal();}catch(e){toast(e.message);}}
function selectedData(){const d=state.inspection,key=$('upstream-select').value;return key==='result'?{body:d.response,data:d.result}:d.upstream[Number(key)];}
function renderInspection(){const d=state.inspection;if(!d)return;document.querySelectorAll('[data-tab]').forEach(b=>{const active=b.dataset.tab===state.tab;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));});$('upstream-select').hidden=!['upstream','tree'].includes(state.tab);$('field-search').hidden=state.tab!=='tree';const content=$('inspect-content');content.replaceChildren();if(state.tab==='tree'){const target=selectedData();if(target.data==null){content.append(el('p','muted','此响应是纯文本，请在阅读输出或原文标签查看。'));return;}if($('field-search').value){renderFieldSearch(content,target.data,$('field-search').value);return;}content.append(jsonNode('$',target.data,true));return;}let value=state.tab==='request'?JSON.stringify({request:d.request,metrics:d.metrics},null,2):state.tab==='upstream'?selectedData().body:d.response;const pre=el('pre',null,(value||'没有返回数据。').slice(0,18000));content.append(pre);if(value&&value.length>18000){const more=el('button','small-button','展开完整原文（'+bytes(new TextEncoder().encode(value).length)+'）');more.style.marginTop='16px';more.addEventListener('click',()=>{pre.textContent=value;more.remove();});content.append(more);}}
function jsonNode(key,value,open=false){if(typeof value==='string'&&['variable','fanqie'].includes(key)){try{return jsonNode(key+' [JSON]',JSON.parse(value),open);}catch{}}if(value!==null&&typeof value==='object'){const node=el('details','json-node'),summary=el('summary'),entries=Object.entries(value);summary.append(el('span','json-key',key),document.createTextNode(Array.isArray(value)?' ['+entries.length+']':' {'+entries.length+'}'));node.append(summary);let loaded=false;function populate(){if(loaded)return;loaded=true;let offset=0;const more=el('button','small-button','展开更多字段');function chunk(){const next=entries.slice(offset,offset+100);next.forEach(([k,v])=>node.insertBefore(jsonNode(k,v),more));offset+=next.length;more.textContent='展开更多（剩余 '+(entries.length-offset)+' 项）';more.hidden=offset>=entries.length;}more.addEventListener('click',chunk);node.append(more);chunk();}node.addEventListener('toggle',()=>{if(node.open)populate();});if(open){node.open=true;populate();}return node;}const line=el('div','json-leaf');line.append(el('span','json-key',key+': '),el('span','json-value',typeof value==='string'?JSON.stringify(value):String(value)));return line;}
function renderFieldSearch(content,value,query){const q=query.trim().toLowerCase();let count=0;function visit(v,path){if(count>=150||!v||typeof v!=='object')return;for(const [key,item]of Object.entries(v)){if(count>=150)return;const next=path+'.'+key;if(key.toLowerCase().includes(q)){const row=el('div','field-result');row.append(el('code',null,next),el('span',null,item!==null&&typeof item==='object'?(Array.isArray(item)?'数组 '+item.length+' 项':'对象 '+Object.keys(item).length+' 个字段'):String(item)));content.append(row);count++;}visit(item,next);}}visit(value,'$');if(!count)content.append(el('p','muted','没有匹配的字段。'));if(count>=150)content.append(el('p','muted','显示前 150 个匹配；可缩小查询或下载全部数据。'));}
function inspectionDownload(){const d=state.inspection;if(!d)return;const value=state.tab==='request'?JSON.stringify({request:d.request,metrics:d.metrics},null,2):state.tab==='upstream'?selectedData().body:state.tab==='tree'?JSON.stringify(selectedData().data,null,2):d.response;download(value,'request-'+d.record.id+'-'+state.tab+'.'+(state.tab==='result'&&d.result==null?'txt':'json'));}
$('refresh').addEventListener('click',refresh);$('auto-refresh').addEventListener('click',()=>{state.auto=!state.auto;$('auto-refresh').setAttribute('aria-pressed',String(state.auto));$('auto-refresh').replaceChildren(el('span','dot'+(state.auto?'':' off')),document.createTextNode(state.auto?'自动刷新':'已暂停刷新'));});
$('record-search').addEventListener('input',renderAllRequests);$('record-status').addEventListener('change',renderAllRequests);
$('operation').addEventListener('change',updateArguments);$('call-form').addEventListener('submit',sendRequest);$('expand-result').addEventListener('click',()=>previewResult(true));$('result-download').addEventListener('click',()=>download(state.result,'fanqie-response.json'));$('inspect-latest').addEventListener('click',()=>state.latestId?inspect(state.latestId):toast('等待请求记录同步后再试'));
$('apply-address').addEventListener('click',()=>{try{state.base=validBase($('public-base').value);sessionStorage.setItem('relay.base',state.base);renderSource();toast('服务地址已应用，书源已同步更新');}catch(e){toast(e.message);}});
$('copy-source').addEventListener('click',()=>copy($('source-url').textContent));$('copy-address').addEventListener('click',()=>copy(state.base));
$('download-source').addEventListener('click',async()=>{try{const {raw}=await fetchApi('/source.json?base='+encodeURIComponent(state.base));download(raw,'fanqie-rust.json','application/json;charset=utf-8');toast('书源已下载，导入阅读即可使用');}catch(e){toast(e.message);}});
$('token-button').addEventListener('click',()=>{$('service-token').value=state.token;$('token-dialog').showModal();});$('close-token').addEventListener('click',()=>$('token-dialog').close());$('token-form').addEventListener('submit',e=>{e.preventDefault();state.token=$('service-token').value.trim();sessionStorage.setItem('relay.token',state.token);$('token-dialog').close();refresh();});
$('close-inspector').addEventListener('click',()=>$('inspector').close());document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{state.tab=button.dataset.tab;renderInspection();}));$('upstream-select').addEventListener('change',renderInspection);$('field-search').addEventListener('input',renderInspection);$('download-inspection').addEventListener('click',inspectionDownload);
updateArguments();renderSource();refresh();setInterval(()=>{if(state.auto&&!document.hidden)refresh();},3000);

function isFeature(op){return ['discovery_menu','review_summary','reviews','review_replies','shelf_change'].includes(op);}
function featureFields(op,wrap){
    if(!isFeature(op))return false;
    const examples={discovery_menu:{preferences:{gender:'1'}},review_summary:{book:{bookUrl:'6883748331202284558'},chapter:{url:'6883749008234250760'}},reviews:{book:{bookUrl:'6883748331202284558'},chapter:{url:'6883749008234250760'},scope:'book',page:1,sort:1},review_replies:{book:{bookUrl:'6883748331202284558'},chapter:{url:'6883749008234250760'},scope:'book',reviewId:'comment:请填评论ID',page:1},shelf_change:{book:{bookUrl:'6883748331202284558'},action:'add',dryRun:true}};
    const label=el('label',null,'参数（JSON）'),input=el('textarea');input.id='arg-feature';input.rows=14;input.spellcheck=false;input.value=JSON.stringify(examples[op],null,2);input.addEventListener('input',syncRequest);label.append(input);wrap.append(label);
    wrap.append(el('p','field-help',op==='shelf_change'?'dryRun 默认预检查。实际增删需账号会话及 dryRun:false。':'评论 scope 可选 book、chapter、paragraph；段评传 paraIndex。分类筛选在 explore.preferences 中填写。'));syncRequest();return true;
}
function featureRequest(operation){return {operation,args:JSON.parse($('arg-feature').value),device:state.device||{deviceType:'Android',deviceBrand:'Generic'},osVersion:'13'};}
